before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    binary: brev
    ldflags:
      - -X github.com/brevdev/brev-cli/pkg/cmd/version.Version={{.Tag}}

brews:
  - name: brev-cli
    # GitHub/GitLab repository to push the formula to
    tap:
      owner: brevdev
      name: brev-cli
      # Optionally a token can be provided, if it differs from the token provided to GoReleaser
      # token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    # The project name and current git tag are used in the format string.
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://docs.brev.dev"
    plist: |
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
          <key>Label</key>
          <string>dev.brev</string>
          <key>ProgramArguments</key>
          <array>
            <string>brev</string>
            <string>run-tasks</string>
          </array>
          <key>KeepAlive</key>
          <true/>
      </dict>
      </plist>

archives:
  - format_overrides:
      - goos: windows
        format: zip
release:
  github:
  prerelease: auto
# dockers:
#   - image_templates:
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:latest"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
#       - "docker.pkg.github.com/brevdev/brev-cli/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
#     build_flag_templates:
#       - "--pull"
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.name={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
#       - "--label=org.opencontainers.image.source={{.GitURL}}"
