name: e2etest-Test_NoUserBrevNoProj

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:


env:
  BREV_SETUP_TEST_CMD_DIR: /home/brev/workspace/actions-runner/_work/brev-cli/brev-cli

jobs:
    if: github.actor!= 'depbot'   # ignore the pull request which comes from user depbot.
  Test_NoUserBrevNoProj:

    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
      - name: expire test cache
        run: go clean -testcache
      - name: test
        run: go test -timeout 240s -run ^Test_NoUserBrevNoProj$ github.com/brevdev/brev-cli/e2etest/setup

      - name: Report Status
        if: always()
        uses: ravsamhq/notify-slack-action@v1
        with:
          status: ${{ job.status }}
          notify_when: 'failure'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.ACTION_MONITORING_SLACK }}
